### ISSUE TITLE
Confused between main and master

### ISSUE THREAD

**Issue by buybackoff** [austindonisan/1brc#2]
You main branch is broken with some warnings as errors. But your master branch seems to be newer than main. What should I use?

On some previous commit I used default GCC from build-essential and it was almost as fast and did not change relative ordering of the results, so it's simpler. Do you think it's OK or the code depends on clang for correctness or something?

Also your 10K numbers are very slow, so that I cannot run them regularly. Is that expected? Or maybe it was fixed in the later commits that I cannot build from main's head?

**Comment by austindonisan** [comment]
I don't really understand git and messed up the branches somehow. I didn't mean to create 2, I'll try to fix it.

For me clang produces noticeably better code (~10% faster).

Yeah it's super slow for the 10k branch. The hash size is hard coded to a low value right now and parsing a city longer than 31 bytes is like 5x slower than shorter ones.

**Comment by austindonisan** [comment]
It should be fixed with just the master branch existing now.

I re-tested clang 17 vs gcc 13 and it's 12% faster for the default data set.

In one of the branches there was a bug that with long cities than caused long cities (like in the 10k data) hang or fail. With it fixed the 10k data should only be 5x slower than the default data.

**Comment by buybackoff** [comment]
Your default is so fast that 5x slower than that is almost OK 😉 

I will use clang if 12% turn out to be a dealbreaker.

Could I use just the fault one from: `sudo apt install clang`? 17th requires additional steps.

**Comment by austindonisan** [comment]
The different clang versions don't mater much (+/- 1%). Clang 17 has a couple of tiny automatic optimizations that are missing in <= 16, but I can just hardcode those.

Clang 13 and 14 have better register allocation and are actually the fastest right now. I'll dig into why and get 15+ to do the same.
